# Site settings
title: Imperfectos.org
email: info@interludio.org
emailformspree: 123queso123queso@gmail.com
description: "La palabra PERFECTO significa que ya está completo. Nosotros somos IMPERFECTOS porque aún no hemos acabado, vamos por más. Este es el espacio de las buenas ideas para la gente imperfecta. Blog, libros, podcast, ideas, cursos y charlas sobre liderazgo, espiritualidad, superación y cotidianidad."
slogan: Buenas ideas<br/> para la gente imperfecta
baseurl: ""
url: "https://www.imperfectos.org" # the base hostname & protocol for your site

#Redes Sociales
redes:
 - nombre: facebook
   url: https://www.facebook.com/imperfectos.org/
 - nombre: twitter
   url: https://twitter.com/yahvista

twitter_username: yahvista
facebook_username: jose.chacona

#About Me
aboutme: Una breve descripción mía

#Header Image
header_img: header.jpg

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
    style: compressed

collections:
  frases:
    output: true
    permalink: /frases/:path/

defaults:
  - scope:
      path: ""
      type: frases
    values:
      layout: frase

plugins:
  - jekyll-srcset
  - jekyll-paginate
  - jekyll-sitemap

srcset:
  cache: "/tmp/images"

paginate: 5
paginate_path: "/blog/page:num/"

repository: guayom/imperfectos.github.io
