---
layout: post
title: Tres conceptos que la Iglesia debe aprender de Apple
date: 2012-01-02 19:27:22.000000000 -06:00
type: post
published: true
status: publish
categories:
- Teología y Biblia
tags: []
meta:
  _edit_last: '30508904'
  _wpas_skip_twitter: '1'
  _wpas_skip_fb: '1'
author:
  login: lospalimpsestos
  email: yahvista@hotmail.com
  display_name: Los Palimpsestos
  first_name: ''
  last_name: ''
---
<p><a href="http://lospalimpsestos.files.wordpress.com/2012/01/401327_10150548446235973_563820972_11029341_1001585149_n.jpg"><img class="aligncenter size-full wp-image-14" title="401327_10150548446235973_563820972_11029341_1001585149_n" src="{{ site.baseurl }}/assets/401327_10150548446235973_563820972_11029341_1001585149_n.jpg" alt="" width="300" height="300" /></a></p>
<p>¿Qué tiene que ver la compañía tecnológica más visionaria del mundo, <em>Apple Inc.</em>, con una de las instituciones más antiguas del planeta, la Iglesia?.</p>
<p>A decir verdad, habría que hacer un gran esfuerzo para poder establecer relación alguna entre una y otra organización. Aún más complicado sería hacer una comparación directa entre un líder eclesiástico y Steve Jobs, uno de los fundadores y el alma de Apple. Pero es precisamente por esa distancia que las separa y que las hace diferentes en todos los sentidos, que es importante observar más de cerca la situación.</p>
<p>El 1 de Abril de 1976 se funda Apple Computer. Dos jóvenes inquietos que compartían mucho más que su primer nombre (Steve Wozniak y Steve Jobs) iniciaron el sueño revolucionario de cambiar el mundo y que, a través de una intensa carrera llena de vicisitudes, pervive hasta hoy como la compañía tecnológica más innovadora.</p>
<p>Por su parte, la Iglesia da sus primeros pasos de la mano de un grupo de jóvenes revolucionarios que también soñaban con cambiar el mundo. Este pathos inicial compartido las catapultó a ambas en sus inicios convirtiéndolas en hitos históricos, cada una en su campo y en su época. Sin embargo algo sucedió en el camino. Una de las dos organizaciones no logró preservar ese primer pathos. Lo fue perdiendo paulatinamente a través de los siglos hasta degenerar en una organización completamente diferente.</p>
<p>El 8 de Abril de 1966, exactamente 10 años y 7 días antes de que Wozniak y Jobs fundaran Apple, un artículo de John T. Elson, publicado en la revista <em>Time</em> se atrevía, por fin, a poner sobre la mesa el tema. Llevaba siglos esperando ser sacado a la luz. La portada de <em>Time</em> contenía una pregunta: “¿Ha muerto Dios?”. Y este ejemplar resultó ser el más vendido en más de 20 años. 3,500 cartas llegaron a la oficina del director, un número de cartas nunca antes recibido por la dirección de la revista (tampoco después).</p>
<p>El artículo, de seis páginas, se intitulaba «Hacia un Dios Escondido» y comenzaba así: «¿Dios ha muerto? es una pregunta que excita tanto a los creyentes, quienes secretamente temen que así sea…». Más de 300 entrevistas realizadas por 30 corresponsales aportaron el contenido. Lo interesante de la pregunta de portada es que no ponía en duda la existencia de Dios, pero sí ponía sobre el tapete su posible muerte o, en el major de los casos, su eventual ocultamiento ¿Se habrá escondido Dios?.</p>
<p>Hacía ya mucho tiempo que la Iglesia había empezado a palidecer. El Dios de la Iglesia no había muerto, pero la Iglesia de Dios se desangraba, estaba herida y buena parte de ella estaba muriendo.</p>
<p>¿Qué había sucedido? La Iglesia había pasado de ser un movimiento que liberaba al ser humano (Jn. 8:32) a ser un régimen que imponía pesadas cargas y exigencias cada vez más drásticas (Lc. 11:46). La fe había pasado de ser propiedad del pueblo (Mc. 11:23) a ser propiedad privada, administrada por un imperio. Con el correr de los siglos la Iglesia pasó de ser perseguida a ser perseguidora, de ser un grupúsculo marginal a ser un poder que marginaba. Cambió sus máximas de amor y respeto por una dictadura implacable. La Iglesia pasó de ser diálogo a ser monólogo, pasó de la humildad al orgullo, de la carencia a la ostentación, del phos hilaron a la penitentia… del kerigma al dogma.</p>
<p>Había perdido su rumbo. Y esto se aplica a toda la Iglesia, en todas sus expresiones y tradiciones. A través de un largo y doloroso proceso la Iglesia se había divorciado de la gente y la gente ya no creía en ella. Había, claro, algunas excepciones en las que la esencia cristiana brillaba con fuerza renovada. Pero éstas llamas desaparecían casi tan espontáneamente como habían aparecido.</p>
<p>Así las cosas, asistimos no a la muerte de Dios sino a la convalecencia de su Iglesia. ¿Qué podemos hacer? He aquí las ideas que la Iglesia puede aprender de una compañía visionaria que ha logrado resucitar y reinventarse.</p>
<p><strong>1. Integridad.</strong></p>
<p>Los padres adoptivos de Steve Jobs no eran creyentes fervorosos, pero asistían regularmente a la iglesia luterana. A los 13 años, en 1968, Jobs encontró en casa la edición de Julio de la revista <em>Life.</em> La portada ostentaba una dolorosa fotografía de dos desnutridos niños de Biafra. El domingo Steve llevó la revista a la iglesia y le preguntó al pastor “Si levanto un dedo ¿sabrá Dios cuál voy a levantar incluso antes de que lo haga?” la respuesta del pastor fue afirmativa, a lo que Jobs replicó mostrando la revista: “¿Entonces sabe Dios lo que les ocurre y lo que les va a pasar a estos niños?”. Nunca más regresó a ninguna iglesia.</p>
<p>Es una pregunta que asalta a muchas mentes, sobre todo en los años de la adolescencia. La falta de una respuesta adecuada por parte de los líderes eclesiásticos deja un mal sabor de boca. Ante tales cuestiones la Iglesia parece decirnos una y otra vez que no hilemos tan fino, que creamos ciegamente sin más. Pero esto no satisface a aquellos que, como Steve Jobs, tienen una sensibilidad innata por los detalles más nimios.</p>
<p>Una vez, Jobs y su padrastro estaban construyendo una cerca de madera. El padre le dijo “Tienes que dejar la parte trasera tan bien acabada como si fuera la delantera”. Esto marcó de por vida a Steve. Se obsesionaba por los detalles que nadie iba a ver de cada aparato. Se esmeraba por lograr que cada parte oculta de un producto tuviera un acabado tan cuidado como cualquier fachada. Su biografo, Walter Isaacson, describe cómo una vez “Se aseguró de que los tornillos del interior de la máquina estuvieran recubiertos por un caro cromado, e incluso insistió en que el acabado negro mate se aplicara también al interior de la carcasa cúbica, a pesar de que solo los técnicos de reparación podrían verlo”.</p>
<p>Para cuando acabaron de diseñar el Macintosh “Jobs reunió a todo el equipo para una ceremonia. «Los verdaderos artistas firman su obra», afirmó, y entonces sacó un cuaderno y un bolígrafo de la marca Sharpie e hizo que todos ellos estamparan su firma. Las firmas quedaron grabadas en el interior de cada Macintosh. Nadie las vería nunca, a excepción de algún técnico de reparación ocasional, pero cada miembro del equipo sabía que su firma estaba ahí dentro”.</p>
<p>La integridad se preocupa de los detalles. La falta de integridad, por el contrario, se preocupa de las generalidades, de lo más visible y pierde cuidado de las cosas que no son tan públicas o evidentes. La integridad llama a cuidar todo aquello que nadie ve tanto como si todos lo pudieran ver. El salmista lo sabía perfectamente y exclamó “Quiero conducirme en mi propia casa con integridad de corazón” (Sal. 101:2).</p>
<p>Apple nos enseña a cuidar lo que “nadie ve” pero que sabemos que está ahí. Y eso es algo que la Iglesia debe recordar. Los grandes escándalos sexuales, la mala administración del dinero y de los bienes, el intento infructuoso de representar una hierocracia perfecta e intachable, los discursos de amor al prójimo manchados por brotes de discriminación en contra de algunos sectores de la sociedad (p.e. las mujeres y los homosexuales), el odio a otras religiones (p.e. El Islam), su generalizada adhesión acrítica a las cusas sionistas en detrimento de los Derechos Humanos de los palestinos o su doble moral cuando rechaza de forma pertinaz el aborto o la fecundación in vitro en su discurso de defensa de la vida, pero celebra alegremente el asesinato de Bin Laden incurriendo en una flagrante contradicción. Todo esto ha creado una mala imagen de la Iglesia, como la de un producto embellecido en los grandes ejes de su funcionamiento pero con un acabado poco atendido ahí, en el interior de la “carcasa”.</p>
<p><em>“Después entraron los sacerdotes dentro de la <strong>casa</strong> de Jehová para <strong>limpiar</strong>la. Sacaron toda la impureza que hallaron en el templo de Jehová al atrio de la <strong>casa</strong> de Jehová; y de allí los levitas la llevaron fuera al torrente Cedrón”.</em> <strong>2 Crónicas 29:16</strong></p>
<p><strong>2. Sencillez.</strong></p>
<p>Steve Jobs fue uno de los primeros en promover interfaces de usuario sencillas, al alcance de cualquier novato. En el folleto del Apple II se podía leer la frase, atribuida a Leonardo Da Vinci: “La Sencillez es la máxima sofisticación”. Otra de las obsesiones del cofundador de Apple era la sencillez. “Las casas en las que vivió, independientemente de lo rico que fuera, no eran ostentosas y estaban amuebladas con tanta sencillez que habrían hecho enrojecer de vergüenza a un cuáquero”, afirma su biógrafo.</p>
<p>Jobs fue muy influenciado por la Escuela de la Bauhaus, fundada en 1919 por Walter Gropius en Alemania. Gropius era la tercera generación de arquitectos de su familia y se dedicó principalmente a la innovación tanto en el diseño como en los materiales utilizados. Aquella influencia llevó al padre del iphone al extremo de crear, junto a sus diseñadores, el primer smartphone cuya pantalla táctil lo hacía poseer un único botón en su parte inferior. Durante el proceso de creación del ipod, Jobs exigió a los diseñadores crear un aparato tan sencillo que no requiriera más de tres pasos para alcanzar la acción deseada.</p>
<p>A pocas personas les puede gustar algo que no entiendan. Y cualquier ser humano puede enamorarse de un teléfono con un solo botón, un aparato que no necesite más de tres acciones para alcanzar cualquiera de sus funciones y, finalmente, un artefacto ubicado a medio camino entre un smartphone y un computador, tan intuitivo y sencillo que solo necesite los dedos de las manos para su gestión.</p>
<p>¿Cuánto podría aprender la Iglesia de la sencillez de Apple? Una vez más el salmista lo sabía con claridad: “El Señor protege a la gente sencilla” (Sal. 116:6). La palabra hebrea פתאים puede traducirse por sencillos, simples e incluso sinceros; la Vulgata habla de “niños” o “párvulos” (custodit parvulos). La Biblia valora la sencillez de los niños (Mt. 18:3; Sal. 8:2) y desprecia la ostentación y la vanagloria de los sacrificios cultuales vacíos (Sal. 40:6; Sal. 51:16; Pr. 21:3; Is. 1:11; Mt. 9:13; Mt. 12:7).</p>
<p>Hoy la Iglesia es una institución compleja y burocrática. La sencillez de las palabras de Jesús han sido trastocadas con una vasta perorata. Su forma es practicamente ininteligible. El creyente se siente incapaz de comprender su funcionamiento. Al ver todo esto el Vaticano II propuso grandes avances en la liturgia. Menos genuflexiones tanto del sacerdote como de los creyentes, el uso de la lengua vernácula en lugar del incomprensible latín, el canto de los creyentes, la misa dictada de frente y ya no de espalda. Sin embargo los engranajes de la Iglesia siguen siendo tan complejos e incomprensibles como los circuitos y chips de un computador. La iglesia evangélica parece estar más preocupada por impresionar al mundo que por convencerlo. Ha confundido la palabra “prosperidad” con la palabra “dinero”. Ha invertido cuantiosas sumas de dinero en construir edificios y oficinas y ha olvidado dar vivienda, cobijo y comida al desposeído.</p>
<p>Es significativo que en los escritos apologéticos del siglo II, a excepción de algunos esporádicos pasajes de Justino, apenas se emplea la palabra ekklesía (se proponían defender a Dios y a Cristo, no propiamente a la Iglesia); en cambio, en los padres eclesiasticos posteriores, la Iglesia es el principal tema de su defensa. Esto se debe, sobre todo, a que al principio la Iglesia como institución no necesitaba ser defendida, era sencilla. Pero poco después se vio envuelta en su propia complejidad, quedando atrapada y confundida en sus propias discusiones.</p>
<p>El creyente de hoy necesita toda una vida para comprender la fe de su iglesia, sus dogmas, sus sacramentos y sus estatutos; mientras que la fe del Nuevo Testamento era sencilla, el creyente podía comprenderla de inmediato. Ahí donde Jesús decía fe, el creyente era salvo; ahí dónde Jesús decía gracia, el creyente era perdonado; ahí donde Jesús decía sígueme, el creyente era comisionado.</p>
<p><em>"La habilidad para simplificar signifca eliminar lo innecesario para que lo necesario pueda hablar”</em> - Hans Hofmann.</p>
<p><strong>3. Cambiar el mundo.</strong></p>
<p><em>“Las personas lo suficientemente locas como para pensar que pueden cambiar el mundo son las que lo cambian”.</em> Anuncio «Piensa diferente» de Apple en 1997.</p>
<p>Steve Jobs vivió con una casi arrogante certeza de que había nacido para cambiar el mundo. Logró infundir esta certidumbre a todos aquellos que trabajaban en su compañía. “Estamos inventando el futuro” les decía una y otra vez a sus acólitos más cercanos. “El cristianismo pierde toda su gracia cuando se basa demasiado en la fe, en lugar de hacerlo en llevar una vida como la de Jesús o en ver el mundo como él lo veía” le dijo a Walter Isaacson, su biógrafo. Y, una vez más, en esto también tuvo algo de razón.</p>
<p>Creo que la fe centrada en la fe se vuelve ciega, pero la fe centrada en la imitación de Jesús y en la forma en que éste veía el mundo anima al creyente a abrir los ojos, ver el mundo y actuar en él. Mateo 13:35 nos habla de la Iglesia como la Luz del mundo y el versículo 38 describe el mundo como el campo de siembra donde los creyentes deben tirar la semilla para producir cambios. ¿Cuándo dejó la Iglesia de creer que podía cambiar el mundo?</p>
<p>Creo firmemente que una de las cosas que hizo que Apple esquivara su extinción fue la convicción de su fundador de que estaba destinado a cambiar el mundo. Y así lo hizo. ¿Ha perdido la Iglesia la convicción de que puede cambiar el mundo? ¿No está demasiado centrada en sí misma y en sus programas y servicios dominicales?</p>
<p>Mi respuesta es si, la Iglesia ha dejado de creer que puede cambiar el mundo. Ha empezado a vivir para ella, ha adquirido un lenguaje que solo comprende ella, ya no le habla al mundo, habla acerca del mundo. Esto quiere decir que el cristianismo ha dejado de creer en sí mismo, en la Iglesia, en su misión. Ni la admiración ni la crítica de la Iglesia son decisivas para ella, lo decisivo es la fe de la Iglesia. La Iglesia misma debe creer (fe de la iglesia, genitivo subjetivo: <em>ecclesia credens</em>), y que el hombre crea en la realidad de la Iglesia, o de Cristo en la Iglesia (genitivo o acusativo objetivo: <em>credens ecclesiam</em>).</p>
<p>Cuando Jobs intentaba convencer a alguien para que trabajara en su compañía solía decirle una frase retadora: “¿Quieres pasarte el resto de tu vida vendiendo agua azucarada o quieres una oportunidad para cambiar el mundo?”. La mayoría de la gente no sabía reaccionar ante tales arrebatos de fe. Aún cuando se encontraba en su peor momento, habiendo sido despedido de su propia empresa y sintiéndose exiliado de todo lo que amaba y de todo en lo que creía, Jobs estaba convencido (y decidido a convencer a los demás) de que estaba aquí para cambiar el mundo. Su biógrafo narra una escena que llama la atención:</p>
<p><em>Su frustración con Apple resultó evidente cuando pronunció un discurso para una asociación de estudiantes de la Facultad de Estudios Empresariales de Stanford. El acto se celebró en la casa de un alumno, que le pidió que le firmase un teclado de Macintosh. Jobs accedió a hacerlo si le permitía eliminar las teclas que le habían añadido al Mac después de su salida de la compañía. Se sacó las llaves del coche del bolsillo y arrancó las cuatro flechas del cursor, que ya había vetado en una ocasión, además de toda la fila de teclas de función. «F1, F2, F3... “Voy cambiando el mundo teclado a teclado”, afirmó con tono inexpresivo. A continuación firmó el teclado mutilado.</em></p>
<p>A la Iglesia le hacen falta muchas personas suficientemente locas que piensen que Dios les ha dado el poder para cambiar el mundo, y que lo hagan.</p>
<p><em>“Ciertamente les aseguro que el que cree en mí las obras que yo hago también él las hará, y aun las hará mayores, porque yo vuelvo al Padre”.</em> (Jn. 14:12).</p>
