---
layout: post
title: Sodoma y Gomorra
date: 2012-06-05 22:00:40.000000000 -06:00
type: post
published: true
status: publish
categories:
- Teología y Biblia
tags: []
meta:
  _edit_last: '30508904'
  _wpas_skip_twitter: '1'
  _wpas_skip_fb: '1'
author:
  login: lospalimpsestos
  email: yahvista@hotmail.com
  display_name: Los Palimpsestos
  first_name: ''
  last_name: ''
---
<p><a href="http://lospalimpsestos.files.wordpress.com/2012/06/biblia_lupa1.png"><img class="size-full wp-image aligncenter" src="{{ site.baseurl }}/assets/biblia_lupa1.png" alt="Image" /></a></p>
<p>Antes de empezar la redacción de estos párrafos debo decir que me estoy limitando al análisis exclusivo del caso de las ciudades de Sodoma y Gomorra. Esto quiere decir que procuraré determinar las razones bíblicas y teológicas que llevaron a la destrucción de ambas poblaciones. En este comentario no intento establecer la pecaminosidad o no de prácticas consideradas por muchas personas como desviaciones de su sexualidad. También debo anticipar que deberé limitarme al análisis de los versículos más importantes y determinantes del relato.</p>
<p>Las ciudades de Sodoma y Gomorra son muy conocidas, quizás sean de las más famosas de toda la Biblia. Nos llegan sus noticias desde el Antiguo Testamento. Hoy en día son sinónimo de ciudades pecadoras, sobre todo, y según el pensamiento generalizado, de pecados de índole sexual. La pregunta que procuramos responder en este texto es: ¿Cuál fue el verdadero pecado por el que fueron destruidas estas dos ciudades?</p>
<p>Encontramos el relato en el capítulo 19 del Génesis. Sin embargo se menciona repetidas veces a los largo de la Escritura.</p>
<p>El primer versículo clave se encuentra en Génesis 19:5</p>
<div>
<p><em><span style="font-size:xx-small;"><span class="Apple-style-span" style="line-height:10px;">"</span></span>Llamaron a Lot y le dijeron:</em></p>
</div>
<div>
<p><em>—¿Dónde están los hombres que vinieron a pasar la noche en tu casa? ¡Échalos afuera! ¡Queremos acostarnos con ellos!"</em></p>
<p>Tenemos aquí un texto que ha sido traducido e interpretado, a partir de la Edad Media, con un matiz muy específico. Sin embargo, un estudio más profundo del hebreo en el que fue escrito nos puede ayudar a comprender mejor lo que sucedía. El verbo hebreo <em> yadá, que se traduce como "acostarnos"</em> en el versículo, se traduce más frecuentemente como "conocer".</p>
<p>Este verbo<em> </em>aparece seis veces. En Génesis 18:19 Dios dice de Abraham “lo he conocido”, aludiendo, sin duda alguna, a la alianza solemne establecida en Génesis 17: 2.  En Génesis 18:21 Dios quiere bajar hasta Sodoma para “conocer” los hechos, es decir, “reconocer” o “investigar”.  En el texto que nos ocupa, Génesis 19:5 los habitantes de Sodoma exigen “conocer” a los mensajeros divinos para "reconocer", es decir: interrogarlos. En Génesis 19:8 las hijas de Lot no han “conocido marido”, o sea, no están casadas pero sí están prometidas (19:14). Por último, en 19:33 y 19:35, cuando las jóvenes se acuestan (Heb. s<em>hákhab)</em> incestuosamente con su padre, él no “conoce” lo que pasa.</p>
<p>En el primer caso la palabra es utilizada como forma de conocimiento formal de un tratado o pacto. En el segundo caso, la misma palabra se utiliza para denotar conocimiento intelectual, analítico. En el tercer caso, se repite la noción de interrogar al extranjero para investigarlo inquisitivamente, casi de seguro con violencia. En el cuarto caso se habla de las hijas de Lot como vírgenes, y en los dos últimos casos se utiliza otra palabra para describir el acto sexual y se vuelve a utilizar <em>yadá</em> para demostrar la inocencia de Lot, ya que él no tenía conocimiento de lo que sucedía.  (Para un estudio más completo de la palabra véase: http://concordances.org/hebrew/3045.htm).</p>
<p>Debemos reconocer que la Biblia Hebraica, para hablar específicamente de la vida sexual,  recurre con más frecuencia a dos verbos: “llegar” (<em>boo</em>) y “acostarse” (<em>shákhab)</em>. Donde “llegarse” a alguien normalmente equivale a “tener relaciones sexuales”. Por ejemplo, Jacob solicita a su tío Labán permiso para llegarse a Raquel (Génesis 29:21). En cuanto a <em>shákhab, </em>la esposa de Potifar pide repetidamente a José que se acueste con ella (Génesis 39:7-12).</p>
<p>Teniendo en cuenta el análisis anterior podemos entender los versículos siguientes (Génesis 19:6) como el afán de Lot por evitar un interrogatorio violento, injusto y vejatorio. Como respuesta, Lot es amenazado con recibir un castigo peor (Génesis 19:9).  La palabra que aparece traducida por "perversidad" en el versículo 8 no describe el tipo de pecado que se iba a realizar, podría traducirse también por "maldad". (Para una profundización de la palabra hebrea http://concordances.org/hebrew/7489a.htm). Es importante saber que las leyes a las que obedecía Lot permitía el comercio de hijas. Las podía regalar o vender (Éxodo 21:7-9). En todo caso, no debemos conjeturar más allá de lo que el texto nos permite, ni tampoco debemos pensar que el episodio de un pecado no realizado (el texto dice que nunca llega a efectuarse), puede ser determinante para el destino de las dos ciudades.</p>
<p>Como anoté más arriba las famosas ciudades de Sodoma y Gomorra vuelven a aparecer en otros textos de la Biblia. Es el caso de los profetas Isaías, Jeremías, Ezequiel, Amós y Sofonías, también se menciona en el libro de Lamentaciones.</p>
<p>En el libro de Isaías se mencionan en 1:9; 1:10; 3:9 y 13:19, pero no se menciona ningún tipo de pecado sexual. Se admite que en esas ciudades sucedía algo atroz, algo inaceptable, pero no se menciona aún qué era lo que sucedía. En este punto, aún no podemos determinar cuál fue el pecado que las llevo a la destrucción.</p>
<p>En Jeremías las encontramos en 23:14; 49:18 y 50:40 pero tampoco podemos encontrar indicios de un pecado únicamente de índole sexual. Me llama la atención el texto de Jeremías 23:14</p>
<p><em>"Y entre los profetas de Jerusalén he observado cosas terribles: cometen adulterio, y viven en la mentira; fortalecen las manos de los malhechores, ninguno se convierte de su maldad. Todos ellos son para mí como <strong>Sodoma</strong>; los habitantes de Jerusalén son como Gomorra." </em></p>
<p>En el que se compara a los profetas de Jerusalén con aquellos habitantes pecadores de Sodoma y Gomorra. Pero aunque se mencionan varios pecados (adulterio, mentira, apoyan a los malhechores), no podemos determinar aún cuál es el pecado que destruye a Sodoma y Gomorra. Lo que sí nos permite este texto de Jeremías es comparar ese pecado (aún no mencionado) con el del adulterio y el de la mentira. Una cosa es segura: el pecado de Sodoma y Gomorra era valorado por Dios exactamente igual que el adulterio y que la mentira.</p>
<p>En el libro de Lamentaciones se mencionan una única vez en 4:6 y, contra todo pronóstico, se menciona que <em>"Más grande que los pecados de <strong>Sodoma</strong> es la iniquidad de Jerusalén..." </em>Es decir, que en Jerusalén se pecaba aún más que en Sodoma y Gomorra. Y ésta última también fue destruida en el año 587 a.C. por el ejército de Nabucodonosor II.</p>
<p>En Ezequiel se mencionan 5 veces: 16:46; 16:48; 16:49; 16:53; 16:56. En este libro podemos encontrar la descripción más importante acerca del pecado de Sodoma y Gomorra, la podemos leer en 16:49-50</p>
<p><em>"Tu hermana Sodoma y sus aldeas pecaron de soberbia, gula, apatía, e indiferencia hacia el pobre y el indigente. <sup>50 </sup>Se creían superiores a otras, y en mi presencia se entregaron a prácticas repugnantes. Por eso, tal como lo has visto, las he destruido."</em></p>
<p>Este texto es revelador. El pecado por el que fueron destruidas va mucho más allá de la perversidad sexual (que de seguro había, al igual que en todas las ciudades). Sus pecados, enlistados claramente fueron: Soberbia, gula, apatía, indiferencia hacia el pobre y el indigente y el orgullo (se creían superiores a otras). Todo lo anterior genera una cultura de "practicas repugnantes", rechazadas por Dios. Por eso fueron destruidas esas ciudades. En todos los textos mencionados hasta ahora, los nombres de Sodoma y Gomorra sirven como ejemplo de una realidad social donde los pobres sufren injusticia, corrupción, opresión y violencia. No es de extrañar que a los extranjeros los quisieran tratar con injusticia y con violencia.</p>
<p>Ya en el Nuevo Testamento podemos encontrarlas mencionadas múltiples veces. (Mt. 10:15;Mt. 11:23; Mt. 11:24; Lc. 10:12; Lc. 17:29; Rom. 9:29; 2 Ped. 2:6; Jud. 1:7; Ap. 11:8).</p>
<p>En los Evangelios, toda vez que se mencionan se utilizan como punto de comparación con el día del juicio final. Poniendo la suerte de las ciudades como mejor que la suerte de los que sean castigados el día del juicio final.</p>
<p>En Romanos y en 2 de Pedro, se mencionan como recordatorio para todos los impíos. Una generalización para todo pecador.</p>
<p>En Judas encontramos un texto llamativo en el que se mencionan pecados sexuales en Sodoma y Gomorra. El texto aparece justo después de mencionar el pecado de los "ángeles" que, evidentemente, no tuvo nada que ver con el homosexualismo. Además, el texto equipara los actos de Sodoma y Gomorra con los de los ángeles desobedientes. La palabra griega utilizada es <em>ekporneusasai</em>(de porneia) que debe traducirse, por norma, como adulterio. (Para una profundización del término véase: http://concordances.org/greek/1608.htm). Unida a esta palabra podemos encontrar una enigmática frase griega que unos pocos han traducido como "actos contra la naturaleza". Sin embargo la gran mayoría de las versiones de la Biblia (tanto en castellano como en inglés) no lo hace así. Literalmente el griego se lee: "Ir tras otra carne" (Podemos ver una comparación de traducciones aquí: http://bibliaparalela.com/jude/1-7.htm). Esta frase no describe el tipo de pecado, aunque puede inducir a la noción de "adulterio" o "fornicación".</p>
<p>Finalmente Apocalipsis las menciona una única vez, donde se habla de la última destrucción de Jerusalén.</p>
<p>Habiendo analizado todos los textos bíblicos acerca de las ciudades Sodoma y Gomorra, debemos desmentir el mito generalizado de que fueron destruidas por un pecado de índole sexual, mucho menos tendiente al homosexualismo. Antes bien, su pecado se enmarca dentro de la injusticia, opresión, orgullo, soberbia, gula, apatía...</p>
</div>
