---
layout: post
title: Interludio, Teología Racklette.
date: 2013-08-01 00:58:02.000000000 -06:00
type: post
published: true
status: publish
categories: []
tags: []
meta:
  _edit_last: '30508904'
  publicize_twitter_user: Interludios
  _wpas_done_1100923: '1'
  _publicize_done_external: a:1:{s:7:"twitter";a:1:{i:200585546;b:1;}}
  geo_public: '0'
  _wpas_skip_1100923: '1'
author:
  login: lospalimpsestos
  email: yahvista@hotmail.com
  display_name: Los Palimpsestos
  first_name: ''
  last_name: ''
---
<p><a href="http://lospalimpsestos.files.wordpress.com/2013/08/raclette-hamilton-beach-31602_mco-f-3983012452_032013.jpg"><img class="aligncenter size-medium wp-image-1409" alt="raclette-hamilton-beach-31602_MCO-F-3983012452_032013" src="{{ site.baseurl }}/assets/raclette-hamilton-beach-31602_mco-f-3983012452_032013.jpg" width="300" height="200" /></a></p>
<p>Durante nuestra luna de miel, Laura y yo, habíamos hecho un feliz descubrimiento culinario. Fue en la ciudad de Múnich, en Alemania. Unos amigos tenían en la mesa un singular aparato octogonal al que llamaban La Raclette. El sino del destino había decidido que solo unos días antes recibiéramos uno de esos artefactos como regalo de bodas. Sorprendidos por la curiosa coincidencia sometimos a nuestros amigos a un intenso interrogatorio con el fin de aprender a utilizar aquél artilugio. Cuando hubimos escuchado sus explicaciones, Laura y yo estábamos enamorados de aquél plato de origen suizo. Durante todo el viaje (recorrimos embelesados las ciudades de Barcelona, Múnich, Viena, Salzburgo y varios pueblitos empotrados en los Alpes austriacos) esa comida fue protagonista de muchas de nuestras conversaciones. Acordamos estrenar nuestra raclette en cuanto regresáramos a casa. Y así lo hicimos.</p>
<p>La palabra raclette viene del francés racler, que significa literalmente raspar. Esta palabra denomina un tipo específico de queso, oriundo del cantón suizo de Valais, que utilizaban los campesinos de los Alpes. Aquellas gentes solían llevar sus ganados a pastar muy lejos de sus casas, pernoctando al cuidado de sus vacas en las frías laderas de las montañas. Por las noches hacían una hoguera a la que acercaban una piedra en la que se derretía un queso que podía llegar a pesar hasta 6 kilogramos. Luego raspaban el queso para verterlo sobre papas asadas. En las amplias soledades de aquellas montañas, los campesinos solían pasar largas horas nocturnas conversando y comiendo entre amigos. La tradición arraigó profundamente y se extendió a otros países. Hoy se fabrican aparatos especialmente diseñados para preparar este platillo. La raclette se coloca en medio de los comensales y todos cocinan juntos mientras comen y conversan. No existe un chef profesional ni un cocinero del día, sino que todos son los creadores del plato, cuya receta puede ser combinada en una variedad de formas prácticamente infinita. Los comensales se sienten libres sin normas definidas de protocolo, propiciando un ambiente festivo, de tolerancia y respeto en medio de la creatividad.</p>
<p>Cuando Laura y yo regresamos de nuestra pausa con sentido en la playa, decididos a echar a andar la Comunidad Interludio, hicimos una cena raclette con las personas que nos acompañarían en el nacimiento de Interludio. El valor supremo de la raclette es su carácter comunitario, algo que deseábamos que también caracterizara a la Comunidad Interludio. Esta sería una comunidad donde todos seríamos bienvenidos sin distinción alguna, donde no existieran grandes estrellas o una élite de sabios o expertos (chefs espirituales), su autoridad sería el amor (cf. 1 Cor. 13), su poder, la Palabra de vida (cf. Jn.1:1), su verdad, el perdón y la comunión regalados no solo a creyentes. Aquélla cena fue el inicio de la Comunidad Interludio. Una cena que definió mucho del carácter y del formato de todo cuanto hacemos. Recordamos juntos que la comunidad de amigos de Jesús se basaba también en una serie de eventos gastronómicos de carácter comunitario. La comunidad de amigos de Jesús era un espacio donde podían converger personas de todo tipo para comer juntos pan y pescado y para alimentarse también de Palabra de vida (Mt. 14:13-21), lo que también podía suceder alrededor de una mesa llena de pecadores (Mc. 2:15-16), sin que los comensales tuvieran que ingerir comida pura o ser la comunidad de las “manos limpias” (Mc.7:1-23). En la comunidad de Jesús sabían muy bien que el amor, si deja de ser gratuito, pierde inmediatamente su esencia y deja de ser amor, convirtiéndose en negocio, intercambio o trueque. Y Jesús no pedía nada a cambio, no quería un trueque equivalente, él solo quería dar su vida en amor gratuito y generalizado (cf. Mc. 6:36-37). Deseábamos que en Interludio reinara el amor gratuito y el respeto mutuo. Porque el amor que no se entrega y la palabra que no sabe dialogar se convierten en ideología. Queríamos evitar a toda costa los excesos del autoritarismo, los legalismos y las estructuras arbitrarias que convierten a la iglesia en una dictadura espiritual y que tantas heridas han causado a creyentes y no creyentes. Dimos inicio a nuestra comunidad reconociendo que ninguno de nosotros es perfecto, que somos todos pecadores y necesitados de la gracia de Dios. De igual forma tomamos la determinación de que en nuestra comunidad debían darse la mano todo tipo de personas en amor, aceptación mutua, tolerancia y respeto. Desde ese día, la raclette se convertiría en nuestro símbolo del amor fraternal, de la comunidad de fe y de las relaciones saludables que nos empeñaríamos en construir (Col. π).</p>
<p><strong>Todos tenemos sed. </strong></p>
<p>En las semanas que siguieron a la cena raclette, en la que siete personas habíamos soñado, comido, reído y creído juntos, mucha gente se empezó a unir al grupo. Nos reuníamos en la sala de nuestra casa. Un salón tan pequeño como acogedor que en poco tiempo empezó a quedarse estrecho. Un día de tantos ya no cupimos, no entraba un alma más. En febrero del 2009 nos trasladamos a un nuevo lugar, más amplio, más céntrico y completamente equipado para la realización de nuestras celebraciones. Un gran número de las personas que se integraban venían heridas y rechazadas por otras comunidades, otros ni siquiera habían visitado un evento cristiano en toda su vida. Cada día venían más personas a nuestras reuniones: católicos, evangélicos, resentidos, decepcionados y buscadores de todo tipo con los que procurábamos poner en práctica nuestros valores de amor gratuito y respeto inquebrantable. Pronto nos percatamos de lo difícil que resultaba ser fieles a estos principios. No obstante nos empeñamos en lograrlo. El amor gratuito no es un concepto comúnmente enseñado, los seres humanos hemos creído el mito de que “nada es gratis” y actuamos condicionados por este pensamiento, incluso en nuestra relación con la iglesia y, lo que es más triste, con Dios. Las ideas erróneas acerca de lo que es la iglesia también dificultaban mucho la práctica de la gratuidad. Impera la noción de ser sirvientes de Dios y súbditos de los líderes eclesiales. Una obediencia obligatoria sin más alternativa que dominar (liderazgo) o ser dominados (comunidad). Yo me preguntaba perplejo ¿Hace cuánto que hemos olvidado que el Dios de Jesús no busca siervos, sino amigos (Jn. 15:15)? Lo que encontramos en el Nuevo Testamento es la conformación de una comunidad de escucha mutua, en la que todos se sirven, acogen y aman (Fil. 2:1-4).</p>
<p>Optamos por presentar a Interludio como una comunidad conformada por gente necesitada. Tal como comenta Drewermann en su diálogo con el obispo Jacques Galliot: “Me gusta mucho la actitud de Jesús ante la samaritana. Está cansado; tiene sed: no lo hace a propósito, no está fingiendo. Comienza por pedir de beber. Antes de proponer la fuente de vida, expresa su necesidad de los demás. La primera cosa que hace no es hablar de Dios, es pedir agua. Creo que la primera actitud que debería adoptar la Iglesia de hoy es la de tener necesidad de los demás y no querer decir «Dios» enseguida”.</p>
