---
layout: post
title: 1000:10:5:1 - Los niños que desaparecieron.
date: 2015-10-02 17:55:39.000000000 -06:00
type: post
published: true
status: publish
categories: []
tags: []
meta:
  _rest_api_published: '1'
  _rest_api_client_id: "-1"
  _publicize_job_id: '15406959119'
  _publicize_done_external: a:1:{s:7:"twitter";a:1:{i:1100923;s:57:"https://twitter.com/Interludios/status/650006253301665793";}}
  _publicize_done_1617638: '1'
  _wpas_done_1100923: '1'
  publicize_twitter_user: Interludios
author:
  login: lospalimpsestos
  email: yahvista@hotmail.com
  display_name: Los Palimpsestos
  first_name: ''
  last_name: ''
---
<p style="text-align:center;"><a href="https://lospalimpsestos.files.wordpress.com/2015/10/captura-de-pantalla-2015-10-02-a-las-11-52-57-a-m.png"><img class="alignnone size-medium wp-image-2219" src="{{ site.baseurl }}/assets/captura-de-pantalla-2015-10-02-a-las-11-52-57-a-m.png" alt="Captura de pantalla 2015-10-02 a las 11.52.57 a.m." width="300" height="190" /></a></p>
<p><em>Vainas humanas vacías, seres del escalafón animal más bajo, intelectualmente muertos.</em> Son solo algunas de las maneras en que se calificaba a las personas con discapacidades durante la época nazi.</p>
<p>Uno de los crímenes más ocultos del nazismo consistió en el asesinato de miles de personas discapacitadas. Los órganos especializados que se dedicaban a esta labor objetaban que estas personas “no eran lo suficientemente productivas, generaban gastos y acaparaban recursos y mano de obra”. Y por esa razón tenían que morir.</p>
<p>Durante los primeros siete años del periodo nacionalsocialista, se realizaron cerca de 350,000 esterilizaciones forzadas. La idea de esta práctica era la de evitar el nacimiento de personas con discapacidades hereditarias. Para el Reich la eliminación de personas “incapaces de trabajar” respondía a la idea de que “el mantenimiento de los que no son aptos para vivir es un lujo”.</p>
<p>Los peritos del Reich habían calculado la cantidad de personas que debían morir, basados en un modelo estadístico. La cifra era el resultado de la relación 1000:10:5:1. Lo que quiere decir que de cada mil personas, diez necesitan asistencia psiquiátrica, médica, hospitalaria o de alguna otra índole. De esas diez, cinco se encuentran en tratamiento hospitalario, y de esas cinco una debe ser incluida en el programa de “redención”. Redención del dolor y del sufrimiento tanto para el paciente como para sus familiares. La relación 1000:10:5:1 se traducía a unas 70,000 personas.</p>
<p>Así que se unían dos razonamientos que justificaban el asesinato de personas enfermas o discapacitadas. Por una parte se trataba de una aplicación de la higiene genética, que buscaba la creación de una raza superior; pero por otra parte había un razonamiento meramente utilitarista, es decir: el ahorro de dinero para el Reich que representaría la eliminación de personas “que previsiblemente nunca serán dadas de alta, que no trabajen lo suficiente como para poder pagar su manutención” (Heilmann, <em>Döblins Fahrt ins Blaue, </em>1988, p.209). Goebbels escribió lo siguiente “Es intolerable que, en plena guerra, tengamos que cargar con el peso de cientos de miles de personas completamente inadecuadas para la vida práctica, que están totalmente entontecidas y nunca podrán sanar”. Los cálculos de ahorro, al aplicar toda esta filosofía, ascendían a más de 880 millones de marcos del Reich, unos 10,000 millones de euros actuales. (Aly, Roth, <em>Restlose Erfassung, </em>1984, p. 93). Todo aquel plan se llegó a denominar Acción T4.</p>
<p>Los bebés que nacían con malformaciones, los niños con discapacidades, problemas de aprendizaje, retrasos motores o intelectuales, eran recluidos en centros pediátricos para ser analizados y, posteriormente, enviados a otros centros donde serían asesinados, ya sea por medio de gaseamientos o mediante inyecciones letales.</p>
<p>El teólogo evangélico Ludwig Schlaich dirigió uno de los centros de reclusión en Stteten. El fue uno de los pocos que protestó enérgicamente contra las medidas nazis. En sus escritos podemos encontrar impresiones testimoniales de lo que sucedía en el centro de reclusión que él dirigía.</p>
<p><em>“La mayoría de nuestros enfermos quedaban perplejos ante la diabólica injusticia de ver cómo su enfermedad, esa cruz inmerecida con la que habían tenido que cargar durante toda su vida, se utilizara ahora para imponerles la pena capital”. </em></p>
<p>El teólogo continúa narrando que un paralítico se quejaba desde su silla de ruedas “¿Adonde puedo huir? ¿Quién me puede esconder? ¿Quién puede protestar por mi?”. Otra paciente gritó mientras la conducían al bus que la llevaría al centro de aplicación de la medida (asesinato): “¿Qué culpa tengo de ser así y de que me hagan esto?”.</p>
<p>Elvira Hempel, de nueve años, pudo sobrevivir a la cámara de gas, aunque su hermana murió producto de la Acción T4. Ella narra lo siguiente, ocurrido el 3 de septiembre de 1940:</p>
<p><em>Tomo una bolsa, la abro y veo dentro mi precioso vestido de flores. Ya no me queda. Voy con la enfermera y le digo que ya no me queda. Ella toma otro del armario y me lo da. Un vestido feísimo, de color rojo. Tiene demasiados botones. Preferiría no ponérmelo, pero si no lo hago me darán una paliza. </em></p>
<p><em>Nos llevaron a todas a otro pabellón donde hay muchas mujeres y también muchos niños. Al fondo hay un escenario. Sobre el escenario hay una mesa con muchos expedientes. A los niños nos llevan a otra habitación donde hay una montaña de ropa y zapatos. Hay una mesa en la que hay personas sentadas con batas blancas. Una mujer dice muy bruscamente “¡Desvistanse, y rapidito!”. Ella ayuda a los niños más pequeños a quitarse la ropa. Se da prisa en hacerlo. A cada niño lo colocan en una fila junto a la mesa donde está la gente con batas blancas. Yo llevo un vestido rojo feísimo con muchos botones y me regañan por tardarme tanto en desvestirme. Cuando estoy desnuda me agarran del brazo y me arrastran a la mesa. Allí un hombre me pregunta el nombre y la edad. El hombre hojea el expediente y me da permiso de vestirme. Somos solo tres los niños que hemos regresado. </em>(Elvira Manthey. <em>Die Hempelche. Das Schicksal eines deutschen Kindes, das vor der Gaskammer umkehren durfte, </em>1994, pp. 67-71).</p>
<p style="text-align:center;"><a href="https://lospalimpsestos.files.wordpress.com/2015/10/image013.jpg"><img class="alignnone size-medium wp-image-2218" src="{{ site.baseurl }}/assets/image013.jpg" alt="image013" width="300" height="276" /></a></p>
<p>La Acción T4 contaba también con un registro de “recién nacidos contrahechos”. Mediante un decreto confidencial, emitido el 18 de julio de 1939, se obligaba a inscribir en un registro a los niños que nacían con malformaciones. Los médicos, instituciones, enfermeros y padres, tenían la obligación de informar de la existencia de niños con alguna discapacidad. El decreto se justificaba diciendo que los datos recabados servirían para fines científicos y para la búsqueda de cura y prevención de malformaciones. Había que informar de niños con “retraso, Síndrome de Down, microcefalia, hidrocefalia, malformaciones de cualquier tipo, especialmente de extremidades, fisurales graves de cráneo o columna etc. Parálisis cerebral y otras”.</p>
<p>Según los datos oficiales, a finales del Tercer Reich fueron inscritos alrededor de 100,000 niños con discapacidades, de los cuales unos 5,200 fueron asesinados por medio de la Acción T4, sobre todo por medio de sobredosis de tranquilizantes, principalmente Luminal (Fiscalía de Schwerin, en el escrito de acusación contra Richard von Hegener, 9 de septiembre de 1949). Sin embargo, investigaciones recientes han demostrado que a esos 5,200 niños habría que sumar un número indeterminado de niños, bebés y adolescentes, cercano a los 4500, que fueron llevados a cámaras de gas regentadas por la Acción T4. Las cifras finales de los investigadores ascienden a más de diez mil niños y niñas física o psíquicamente discapacitados, que fueron asesinados entre 1939 y 1945.</p>
<p>Un niño de 4 años, llamado Christian, fue ingresado en 1943 en la clínica de Psiquiatría y Neurología de la Universidad de Heildelberg. Fue clasificado como “muy retrasado” y asesinado el 29 de julio de 1944. En el informe de diciembre anterior se puede leer:</p>
<p><em>El paciente ha estado todo el día de buen humor. Se sienta en su cama, mantiene las manos fijas, mueve todos los deditos de manera muy graciosa, menea el pulgar, grita de diversión. También se tumba boca arriba, levanta las piernas y juega con la punta de los pies o da pataditas en la cama. A veces se mete el dedo pulgar en la boca y lo chupa. El paciente no tiene miedo al agua, le gusta que lo bañen, chapotea, salpica y se mete el bote de jabón a la boca. </em>( Citado por Götz Aly, Los que sobraban).</p>
<p>Me pregunto hasta cuándo seguiremos aceptando las subsiguientes “Acciones T4” de la actualidad. La industria farmacéutica aduce imposibilidad de asumir investigaciones para malformaciones “porque no son rentables”. Los países privatizan la medicina, haciendo que los menos favorecidos enfrenten la imposibilidad de pagar por tratamientos, cirugías, internamientos, terapias y medicamentos. Una forma muy solapada de “higiene genética”, de “redención”, de selección “natural” se cierne sobre nuestras sociedades, que han decidido que la medicina, la salud y la vida, tienen que ver con el dinero y no con el derecho a existir. Cabe preguntarnos de qué otras maneras sutiles o evidentes nuestras sociedades han optado por coartar las libertades de las personas con discapacidades, clasificar sus vidas como personas menos válidas (minusvalía), no válidas (invalidez), no aptas para el trabajo (discriminación laboral), no aptas para emitir criterios, ser elegibles en puestos de gobierno, en fin: es necesario reconocer que, por más espeluznantes que sean los hechos históricos de la Acción T4, nuestras sociedades continúan degradando la validez de la vida digna cuando ésta supone enfermedad, malformación o discapacidad.</p>
