backend:
  name: git-gateway
  branch: netlify-cms
media_folder: "images/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Published", name: "published", widget: "hidden", default: "true"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "img", widget: "image"}
      - {label: "Thumbnail Image", name: "thumb", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
