backend:
  name: git-gateway

publish_mode: editorial_workflow

media_folder: "images"
collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Published", name: "published", widget: "hidden", default: "true"}
      - {label: "extraclass", name: "extraclass", widget: "hidden", default: "sp-single"}
      - {label: "Categories", name: "categories", widget: "hidden", default: "blog"}
      - {label: "Excerpt separator", name: "excerpt_separator", widget: "hidden", default: "<!--more-->"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "img", widget: "image"}
      - {label: "Thumbnail Image", name: "thumb", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
